In [1]:
import numpy as np
import scipy.linalg as la

In [9]:
test_mat = np.random.random((4, 4)) + np.random.random((4, 4))*1j

In [10]:
test_mat

array([[0.86276495+0.22513275j, 0.58383579+0.03938007j,
        0.90460099+0.58636318j, 0.94339296+0.01740009j],
       [0.29459394+0.20240362j, 0.84241307+0.81771447j,
        0.3288105 +0.81874447j, 0.95611293+0.75805393j],
       [0.9353147 +0.48783791j, 0.72965166+0.47665204j,
        0.6365914 +0.19143925j, 0.71323245+0.81054405j],
       [0.53585144+0.85328374j, 0.30078655+0.73148258j,
        0.93192221+0.30125734j, 0.2232171 +0.34540452j]])

In [11]:
w, vl, vr = la.eig(test_mat, left=True)

In [12]:
w

array([ 2.64789452+1.9073338j , -0.6881691 -0.64173444j,
        0.45255655+0.42559161j,  0.15270456-0.11149998j])

In [13]:
vl

array([[ 0.48541774+0.0157002j , -0.26720769-0.32120686j,
        -0.56752269+0.21089374j, -0.36690233+0.36966124j],
       [ 0.48405627-0.05118453j, -0.19465987-0.14953669j,
         0.68472377+0.j        , -0.00368651+0.13684765j],
       [ 0.50797014+0.01582301j,  0.63175767+0.j        ,
        -0.26378048+0.15741918j,  0.66438374+0.j        ],
       [ 0.51856413+0.j        , -0.38689793+0.46515026j,
         0.22092403+0.14637906j, -0.18368605-0.48460919j]])

In [14]:
vr

array([[ 0.3953991 -0.32950725j, -0.15628881+0.34451008j,
        -0.49176987-0.13771246j, -0.22664107-0.38819777j],
       [ 0.53001564+0.j        , -0.39463786+0.17129525j,
         0.82555394+0.j        , -0.40192906-0.08360078j],
       [ 0.47662583-0.18696792j, -0.1317931 -0.46161693j,
        -0.16900535-0.05568799j, -0.05252991+0.48248627j],
       [ 0.43329378-0.06553815j,  0.66433869+0.j        ,
        -0.13885999+0.08192864j,  0.62757299+0.j        ]])

In [21]:
np.around(vl.conj().T@vr, 2)

array([[ 0.91-0.28j,  0.  -0.j  ,  0.  +0.j  , -0.  +0.j  ],
       [-0.  -0.j  , -0.36-0.84j, -0.  -0.j  , -0.  +0.j  ],
       [ 0.  -0.j  ,  0.  -0.j  ,  0.83+0.26j, -0.  +0.j  ],
       [ 0.  -0.j  , -0.  +0.j  ,  0.  -0.j  , -0.22+0.91j]])

In [30]:
(vr@np.diag(w)@np.linalg.inv(vr))-test_mat

array([[-1.44328993e-15+1.66533454e-16j, -9.99200722e-16+1.11022302e-16j,
        -1.66533454e-15-5.55111512e-16j, -1.99840144e-15+3.05311332e-16j],
       [-5.55111512e-17-1.08246745e-15j,  5.55111512e-16+3.33066907e-16j,
         2.22044605e-16-1.66533454e-15j, -3.33066907e-16-1.11022302e-16j],
       [-1.33226763e-15-1.11022302e-15j, -1.11022302e-15-9.43689571e-16j,
        -1.99840144e-15-1.38777878e-15j, -1.88737914e-15-7.77156117e-16j],
       [-2.22044605e-16-9.99200722e-16j, -3.88578059e-16-1.22124533e-15j,
        -6.66133815e-16-1.88737914e-15j, -9.15933995e-16-9.43689571e-16j]])

In [32]:
(vl@np.diag(w.conj())@np.linalg.inv(vl)).conj().T-test_mat

array([[-4.44089210e-16-1.11022302e-15j,  2.22044605e-16+8.32667268e-16j,
        -8.88178420e-16-5.55111512e-16j, -7.77156117e-16+1.66533454e-16j],
       [ 8.88178420e-16-2.10942375e-15j,  3.33066907e-16+9.99200722e-16j,
        -4.99600361e-16-1.22124533e-15j,  0.00000000e+00+1.11022302e-16j],
       [-5.55111512e-16-1.88737914e-15j, -1.44328993e-15+2.77555756e-16j,
        -1.88737914e-15-1.22124533e-15j, -1.66533454e-15-2.22044605e-16j],
       [ 5.55111512e-16-9.99200722e-16j, -7.77156117e-16-2.22044605e-16j,
        -7.77156117e-16-1.27675648e-15j, -7.77156117e-16+5.55111512e-17j]])