In [1]:
import kwant
print(kwant.version.version)
import numpy as np
import scipy.linalg as linalg
import matplotlib.pyplot as plt

1.4.1


## Params

In [4]:
tau_x = np.kron(np.array([[0, 1], [1, 0]]), np.eye(2))
tau_y = np.kron(np.array([[0, -1j], [1j, 0]]), np.eye(2))
tau_z = np.kron(np.array([[1, 0], [0, -1]]), np.eye(2))
sigma_x = np.kron(np.eye(2), np.array([[0, 1], [1, 0]]))
sigma_y = np.kron(np.eye(2), np.array([[0, -1j], [1j, 0]]))
sigma_z = np.kron(np.eye(2), np.array([[1, 0], [0, -1]]))

mu = 0.5
t = -1.
B = 1.
delta = 0.5
alpha_so = 0.5
V_N = np.array([1.25, 2.5, 5.])
E = np.linspace(-2, 2, 101)
print('tau:')
print(tau_x)
print(tau_y)
print(tau_z)

print('sigma:')
print(sigma_x)
print(sigma_y)
print(sigma_z)

e_up = np.array([1, 0, 0, 0])
e_down = np.array([0, 1, 0, 0])
h_up = np.array([0, 0, 1, 0])
h_down = np.array([0, 0, 0, 1])
print(tau_x.dot(e_up))

tauzsigmax = np.kron(np.array([[1, 0], [0, -1]]), np.array([[0, 1], [1, 0]]))
print(tauzsigmax)
print(tau_z@sigma_x)
print(np.matmul(tau_z, sigma_x))

tau:
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]
[[0.+0.j 0.+0.j 0.-1.j 0.-0.j]
 [0.+0.j 0.+0.j 0.-0.j 0.-1.j]
 [0.+1.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+1.j 0.+0.j 0.+0.j]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0. -1. -0.]
 [ 0.  0. -0. -1.]]
sigma:
[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]
[[0.+0.j 0.-1.j 0.+0.j 0.-0.j]
 [0.+1.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.-0.j 0.+0.j 0.-1.j]
 [0.+0.j 0.+0.j 0.+1.j 0.+0.j]]
[[ 1.  0.  0.  0.]
 [ 0. -1.  0. -0.]
 [ 0.  0.  1.  0.]
 [ 0. -0.  0. -1.]]
[0. 0. 1. 0.]
[[ 0  1  0  0]
 [ 1  0  0  0]
 [ 0  0  0 -1]
 [ 0  0 -1  0]]
[[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 0.  0. -1.  0.]]
[[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 0.  0. -1.  0.]]


## Hamiltonian H and V

In [67]:
H = tau_z * (mu-2.*t) + sigma_z*B + tau_x*delta
V = tau_z*t + 1j*np.matmul(tau_z, sigma_x)*alpha_so
print(H)
print(V)
print(V.conj().T)
matrix_1 = np.block([[H - E[0]*np.eye(4), V.conj().T], [np.eye(4), np.zeros((4, 4))]])
matrix_2 = np.block([[-1.*V, np.zeros((4, 4))], [np.zeros((4, 4)), np.eye(4)]])
print(matrix_1)
print(matrix_2)
print(np.matmul(tau_z, sigma_x))

[[ 3.5  0.   0.5  0. ]
 [ 0.   1.5  0.   0.5]
 [ 0.5  0.  -1.5  0. ]
 [ 0.   0.5  0.  -3.5]]
[[-1.+0.j   0.+0.5j  0.+0.j   0.+0.j ]
 [ 0.+0.5j -1.+0.j   0.+0.j   0.+0.j ]
 [ 0.+0.j   0.+0.j   1.+0.j   0.-0.5j]
 [ 0.+0.j   0.+0.j   0.-0.5j  1.+0.j ]]
[[-1.-0.j   0.-0.5j  0.-0.j   0.-0.j ]
 [ 0.-0.5j -1.-0.j   0.-0.j   0.-0.j ]
 [ 0.-0.j   0.-0.j   1.-0.j   0.+0.5j]
 [ 0.-0.j   0.-0.j   0.+0.5j  1.-0.j ]]
[[ 5.5+0.j   0. +0.j   0.5+0.j   0. +0.j  -1. -0.j   0. -0.5j  0. -0.j
   0. -0.j ]
 [ 0. +0.j   3.5+0.j   0. +0.j   0.5+0.j   0. -0.5j -1. -0.j   0. -0.j
   0. -0.j ]
 [ 0.5+0.j   0. +0.j   0.5+0.j   0. +0.j   0. -0.j   0. -0.j   1. -0.j
   0. +0.5j]
 [ 0. +0.j   0.5+0.j   0. +0.j  -1.5+0.j   0. -0.j   0. -0.j   0. +0.5j
   1. -0.j ]
 [ 1. +0.j   0. +0.j   0. +0.j   0. +0.j   0. +0.j   0. +0.j   0. +0.j
   0. +0.j ]
 [ 0. +0.j   1. +0.j   0. +0.j   0. +0.j   0. +0.j   0. +0.j   0. +0.j
   0. +0.j ]
 [ 0. +0.j   0. +0.j   1. +0.j   0. +0.j   0. +0.j   0. +0.j   0. +0.j
   0. +0.j ]
 [ 0

In [107]:
w, vr = linalg.eig(matrix_1, b=matrix_2)
print(w)
print(vr)
print(np.abs(w))
print(np.around(np.abs(w), 14)<1.)
lambda_e = np.diag(w[np.around(np.abs(w), 14)<1.])
print(lambda_e)
phi_e = vr[np.around(np.abs(w), 14)<1.].T
print(phi_e)

[ 3.26687015-1.33513232j  3.26687015+1.33513232j -0.40316306-0.91512816j
 -0.40316306+0.91512816j  0.87399943-0.48592694j  0.87399943+0.48592694j
  0.26229347-0.10719633j  0.26229347+0.10719633j]
[[-0.28572863-0.47708811j  0.28575405-0.47707288j  0.01640334-0.05575483j
  -0.03751583-0.04438731j  0.00494892+0.00304057j -0.00575519+0.00078402j
   0.15688066+0.01476887j  0.15688026-0.0147731j ]
 [ 0.68092701+0.35893268j  0.68094614-0.3588964j  -0.01173273+0.03987946j
  -0.02683375-0.03174867j -0.16320673-0.10027279j -0.18979608+0.02585574j
  -0.17495075-0.13024192j  0.17494723-0.13024665j]
 [ 0.05090166+0.0186418j  -0.05090266+0.01863909j -0.18541578+0.63022668j
   0.42406151+0.50173351j  0.12147637+0.07463402j -0.14126707+0.01924468j
  -0.01098436-0.01073651j -0.01098407+0.0107368j ]
 [-0.10012389-0.1047226j  -0.10012947+0.10471726j  0.07102761-0.24142225j
   0.16244613+0.19220011j  0.56706714+0.34840108j  0.65945268-0.08983662j
   0.03900542+0.01280512j -0.03900508+0.01280617j]
 [-0.023

In [106]:
trial_soln = phi_e.T[0].T[0:4]
trial_lambda = lambda_e[0][0]
print(V.dot(trial_soln)+trial_lambda*(H-E[0]*np.eye(4)).dot(trial_soln)+trial_lambda**2.*V.conj().T.dot(trial_soln))

[-0.08321139-0.03638051j  0.00583795-0.08562826j -0.91124275-0.60017424j
  0.03825547-0.13512208j]


## Lattice properties

In [5]:
a = 10 # angstroms

norbs = 4 # 2 atomic orbitals * 2 spins * particle-hole

lat = kwant.lattice.chain(a)
#chain (1D), cubic (3D), triangular, honeycomb, kagome
print(lat)

<unnamed Monatomic lattice, vectors [10.0], origin [0.0]>


## JJ Hamiltonian + discretization